# Generated by Django 4.2.16 on 2024-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_pwd', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('monthly_income', models.IntegerField()),
                ('monthly_expenditure', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
