# Generated by Django 4.2.16 on 2024-11-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_expenditure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pwd',
            field=models.CharField(default='', max_length=100),
        ),
    ]
