# Generated by Django 4.2.16 on 2024-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardmap', '0003_rename_user_name_user_name_remove_user_user_pwd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
